/**
 * The 20-patient BMI data (`src/data/diabetes-bmi-20.json`, generated by
 * `pnpm gen:datasets` from the course companions; see
 * docs/decisions/2026-10-07-dataset-generators.md) in the two forms the
 * companions use. Shared with `mse-bowl-gd`.
 *
 * The JSON is imported directly (5 KB) rather than through
 * `src/lib/datasets/index.ts`, which statically imports every case dataset.
 */
import diabetesJson from '@/data/diabetes-bmi-20.json';
import type { DiabetesBmi20Dataset } from '@/lib/datasets/diabetes-bmi-20';

export const DATASETS = ['diabetes-bmi-20'] as const;
export type DatasetName = (typeof DATASETS)[number];

const DATA: Record<DatasetName, DiabetesBmi20Dataset> = {
  'diabetes-bmi-20': diabetesJson as unknown as DiabetesBmi20Dataset,
};

export interface XY {
  x: readonly number[];
  y: readonly number[];
}

/**
 * Lecture 2 companion (cell 8): x = 30 · bmi + 25 (the companion's
 * "recentered" BMI axis), y = disease progression. `LinearRegression` on
 * this gives slope 37.37884216052121, intercept −797.0817390343262 (cell 15).
 */
export function lecture2Points(name: DatasetName = 'diabetes-bmi-20'): XY {
  return {
    x: DATA[name].rows.map((r) => r.bmiRecentered),
    y: DATA[name].rows.map((r) => r.target),
  };
}

/**
 * Lecture 4 companion (cell 18): x = scikit-learn's scaled bmi (about
 * [−0.1, 0.1]), y = disease progression / 300; the model adds a column of
 * ones, so θ = (θ_bmi, θ_one).
 */
export function lecture4Points(name: DatasetName = 'diabetes-bmi-20'): XY {
  return {
    x: DATA[name].rows.map((r) => r.bmiScaled),
    y: DATA[name].rows.map((r) => r.target / 300),
  };
}

/** Record ids in row order (`DIAB-422` …), for accessible point labels. */
export function patientIds(name: DatasetName = 'diabetes-bmi-20'): readonly string[] {
  return DATA[name].rows.map((r) => r.id);
}

/** The companions' printed fits, as strings with the printed digits. */
export function companionFits(name: DatasetName = 'diabetes-bmi-20') {
  const parameters = DATA[name].generativeModel.parameters as {
    companion: {
      lecture2: { slope: string; intercept: string };
      lecture4: {
        sklearn: { mse: string; coef: readonly string[]; intercept: string };
        gd: { theta: readonly string[] };
      };
    };
  };
  return parameters.companion;
}
